# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgis/postgis:12-3.0
    ports:
      - "5467:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
